name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Get dependencies
        run: flutter pub get

      - - name: Build APK
  working-directory: gesture_aid_app
  run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gesture_aid_app_apk
          path: build/app/outputs/flutter-apk/app-release.apk

